### ISSUE TITLE
C:D-Bestellung ohne Servernamen auf der rechten Seite

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#119]
## Bereich:

C:D-Bestellung
## User-Story

Ich habe rechts nur ci eingegeben und keinen Servernamen, 
Formular wird akzeptiert, aber dann fehlt Zielsystem:
13  C30554585   Verbindungstyp: CD
        Verfahren: Konzern R_3
        Umgebung: Abnahme
        Endpoint (Quellsystem) 
        Server: wilsdruff
        Endpoint (Zielsystem)

20.03.2017-IK: ??? Unklar, da man auf jeden Fall Servernamen angeben muss!!! noch mal checken!

Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}

**Comment by automatix** [comment]
Der Fehler dürfte nicht mehr auftreten. Wenn so, dann kann das Ticket geschlossen werden.

**Comment by automatix** [comment]
ready for test

**Comment by mw-ft** [comment]
OK: jetzt kommt Fehlermeldung: Es ist weder ein Server (intern/extern), noch ein Cluster für den Zielendpoint angegeben. Erst wenn man einen Servernamen eingibt, kann man speichern.
