### ISSUE TITLE
Blockgrößenangabe

### ISSUE THREAD

**Issue by aleunam** [dbsystel/AutoFIT#191]
## Beschreibung

![block](https://cloud.githubusercontent.com/assets/17876659/19969196/fbd2ef30-a1d7-11e6-983b-547d8a17c22c.JPG)

**Comment by aleunam** [comment]
2 Fehler: Dateiname: Die Eingabe entspricht nicht folgendem Muster: '/^[A-Z0-9\.]*$/'
und:Blockgröße (nur bei fester Blockung): Es wird eine Eingabe benötigt ( obwohl vb)

**Comment by automatix** [comment]
Fehler 1: Die Eingabe entsprach tatsächlich nicht dem Muster. Bloß die Validierungsmeldung ist etwas kryptisch und soll durch eine benutzerfreudlichere ersetzt werden. (Ist also kein Fehler.) Das wird im Rahmen des #202 behandelt werden.

**Comment by automatix** [comment]
Fehler 2: Beim Schalten auf "vb" wird das Feld "Blockgröße" nicht ausgeblendet, obwohl das ursprünglich so gedacht war. Doch da die Implementierung dieses Verhaltens sich in diesem speziellen Fall mit dynamischen Elementen (<kbd>+</kbd> und <kbd>–</kbd>) nur mit verhältnismäsig viel Aufwand möglich gewesen wäre, bin ich einen einfacheren Weg gegangen:

- Hinweis "nur bei fester Blockung" im Feld-Label;
- serverseitige Entfernung der Blockgrößenangabe, wenn "vb" ausgewählt ist.

Somit funktioniert das Formular als vorgesehen.

**Comment by automatix** [comment]
Blockgröße soll eine _optionale_ Angabe sein.
