### ISSUE TITLE
Verzeichnis

### ISSUE THREAD

**Issue by aleunam** [dbsystel/AutoFIT#193]
![manu](https://cloud.githubusercontent.com/assets/17876659/19971427/43e98b9c-a1df-11e6-8c9d-0a25f20a6638.JPG)
![manu1](https://cloud.githubusercontent.com/assets/17876659/19971435/4b34143a-a1df-11e6-97a5-59648ce4f8c5.JPG)

**Comment by aleunam** [comment]
C:\Transfer\PMT\IN --> heute gleicher Fehler

**Comment by mw-ft** [comment]
in Plausibilitätscheck ist definiert:
Endpoint (CD|FTGW) (Linux/Unix|Windows)	Verzeichnis	ja	Zeichen:  .,_+-A-Za-z0-9/	Folgende Zeichen sind zulässig:    .,_+-@A-Za-z0-9  und  /   (d.h. auch Leerzeichen sind nicht zulässig!)

NEU: Wir müssen unterscheiden:
Endpoint (CD|FTGW) (Linux/Unix)	Verzeichnis	ja	Zeichen:  .,_+-A-Za-z0-9/	Folgende Zeichen sind zulässig:    .,_+-@A-Za-z0-9  und  /   (d.h. auch Leerzeichen sind nicht zulässig!)
Endpoint (CD|FTGW) (Windows)	Schnittstellenverzeichnis	ja	Zeichen:  .,_+-A-Za-z0-9\	
Frage: bei Windows-Verzeichnissen auch die Sonderzeichen: .,+- zulassen???

**Comment by automatix** [comment]
Was ist mit `:` bei **Endpoint (CD|FTGW) Windows**, z.B. `C:\path\to\folder`?

**Comment by automatix** [comment]
Implementiert (mit `:` für Windows).

@mw-ft Falls die Zeichen `.,+-` doch nicht zulässig sind, öffne bitte einfach das Ticket wieder (Button <kbd>Reopen issue</kbd>).

**Comment by mw-ft** [comment]
Nach Rücksprache mit Manuela und Enrico:
Schnittstellenverzeichnis Windows darf nur folgende Zeichen enthalten:
 _-A-Za-z0-9\

**Comment by mw-ft** [comment]
Nach Rücksprache mit Manuela und Enrico:
Schnittstellenverzeichnis Windows darf nur folgende Zeichen enthalten:
_-A-Za-z0-9\

**Comment by automatix** [comment]
Implementiert:

- das Feld-Label umbenannt nach "Verzeichnis";
- den regulären Ausdruck angepasst auf `/^[a-zA-Z0-9_-\\\\]*$/` (Zeichen `a-zA-Z0-9_-\`).

**Comment by automatix** [comment]
Den regulären Ausdruck geändert auf `/^[a-zA-Z0-9_:\-\\\\]*$/` (Zeichen `a-zA-Z0-9_:-\`).
