### ISSUE TITLE
Einschränkung der Autovervollständigung für "Umgebung"

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#203]
## IST-Zustand

Momentan werden in der Autocomplete-Liste "Umgebung" alle Umgebungen angezeigt.

## User-Story

Als Frontend-User möchte ich in der Autovervollständigungsliste nur die Umgebungen angezeigt bekommen, die <strike>für mindestens eine LSP verwendet werden, die ihrerseits zum im Feld "Verfahren" ausgewählten Verfahren gehört</strike> im Zusammenhang mit dem ausgewählten Verfahren verwendet werden.

## Erklärung

Das Ziel ist es, die Situation zu vermeiden, dass der Benutzer eine Umgebung ausgewählt hat, für die es keine LSP gibt. Wenn es also für die Kombination Verfahren&Umgebung keine LSPs gibt, soll die Umgebung nicht vorgeschlagen werden.

Da in der Autovervollständigungsliste nur die Verfahren vorgeschlagen werden, für die es LSPs gibt (s. #204), wird davon ausgegangen, dass die Einschränkung der Umgebungsvorschlagsliste nach dem ausgewählten Verfahren ausreicht.

## Akzeptanz-Kriterien

- Ich befinde mich auf einer beliebigen Formular-Erstellungsseite.
- Ich wähle eins der Verfahren (zu denen es LSPs gibt) aus.
- Ich setze den Cursor ins Feld "Umgebung".
- [ ] Ich erhalte Vorschläge mit den relevanten Umgebungen, d.h. nur solchen Umgebungen, für die es für das ausgewählte Verfahren auch LSP gibt.
- Ich trage ein gültiges Verfahren ein, zu dem es keine LSPs gibt. (Die Auswahlliste (s. #204) zeigt mir kein gültiges Verfahren an. Dann kann ich das gewünschte Verfahren nicht auswählen.)
- Ich setze den Cursor ins Feld "Umgebung".
- [ ] Ich erhalte keine Vorschläge.

**Comment by mw-ft** [comment]
Ich befinde mich auf einer beliebigen Formular-Erstellungsseite.
    Ich trage ein gültiges Verfahren ein, zu dem es LSPs gibt.  
    Ich wähle eins der Verfahren (zu denen es LSPs gibt) aus.
    Ich setze den Cursor ins Feld "Umgebung".
    Ich erhalte Vorschläge mit den relevanten Umgebungen, d.h. nur Umgebungen, für die es für das ausgewählte Verfahren auch LSP gibt!

    Ich trage ein gültiges Verfahren ein, zu dem es keine LSPs gibt. Die Auswahlliste (siehe '204) zeigt mir kein gültiges Verfahren an. Dann kann ich das gewünschte Verfahren nicht auswählen.
    Ich setze den Cursor ins Feld "Umgebung".
    Ich erhalte keine Vorschläge.

**Comment by automatix** [comment]
Den Issue-Comment [259618328](/dbsystel/AutoFIT/issues/203#issuecomment-259618328) ins Ticket eingearbeitet.

**Comment by automatix** [comment]
Die Umgebungen werden bereits nach dem ausgewählten Verfahren gefiltert. Ist kein Verfahren ausgewählt, liefert die Autovervollständigung eine leere Lsite (sprich, keine Vorschläge). Somit ist die Anforderung durch die Implementierung des #204 bereits erfüllt.

**Comment by mw-ft** [comment]
siehe auch #203
Ich kann Verfahren KTR auswählen,
dann Umgebung Entwicklung, 
aber es wird kein LSP angezeigt zur Auswahl!!!

Wenn KTR kein LSP hat, dann darf KTR nicht in der Verfahrensliste angezeigt werden
(und natürlich auch die Umgebung Entwicklung)

**Comment by mw-ft** [comment]
im Abrechnungsteil:
Regel:
Umgebungen sollen alle des ausgewählten Verfahrens (siehe #204) angezeigt werden, wenn
- es auf dem LS mindestens eine Position S + P für die Umgebung des ausgewählten Verfahrens gibt, die nicht den Status "beendet" haben
und
- eine order_quantity > 0 für die haben

Vorschlag: Lösung mit view
DL erstellst und beschreibt die view
