### ISSUE TITLE
Einschränkung der Autovervollständigung für "Verfahren"

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#204]
## IST-Zustand

Momentan werden in der Autocomplete-Liste "Verfahren" alle (aktiven) Verfahren angezeigt.

## User-Story

Als Frontend-User möchte ich in der Autovervollständigungsliste nur die Verfahren angezeigt bekommen, zu denen mindestens eine LSP gehört.

## Akzeptanz-Kriterien

- Ich befinde mich auf einer beliebigen Formular-Erstellungsseite.
- Ich trage die ersten `3` Buchstaben eines gültigen Verfahrens ein, zu dem es LSPs gibt.
- [ ] Ich erhalte Vorschläge mit den relevanten Verfahren.
- Ich trage die ersten `3` Buchstaben eines gültigen Verfahrens ein, zu dem es _keine_ LSPs gibt.
- [ ] Ich erhalte keine Vorschläge.

**Comment by automatix** [comment]
Implementiert. Da es in der Datenbank keine LS (Leistungsscheine) ohne LSP (Leistungsscheinpositionen) gibt, wird für das Verfahren lediglich überprüft, ob es mindestens einen LS dafür gibt.

**Comment by mw-ft** [comment]
Ich kann Verfahren KTR auswählen,
dann Umgebung Entwicklung, 
aber es wird kein LSP angezeigt!!!

**Comment by mw-ft** [comment]
Wenn KTR keine LSPs hat, dann darf KTR nicht in der Verfahrensliste angezeigt werden
(und dann natürlich auch keine Umgebung!)

**Comment by mw-ft** [comment]
im Abrechnungsteil:
Regel:
Verfahren soll nur zur Auswahl angezeigt werden, wenn
- es auf dem LS (service_invoice) mindestens eine Position S + P gibt (in mindestens 1 Umgebung), die (die Positionen service_invoice_position) nicht den Status "beendet" haben
und
- eine order_quantity > 0 für die haben

Vorschlag: Lösung mit view
DL erstellst und beschreibt die view
