### ISSUE TITLE
2 Aufträge mit der selben ChangeNr

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#208]
## User-Story
Es wurden 2 Aufträge mit der selben ChangeNr erstellt
C30589735  mit Order #2 und #4
## Akzeptanz-Kriterien
Die ChangeNr muss eineindeutig sein, d.h. je ChangeNr darf es nur eine Bestellung geben!!!

**Comment by mw-ft** [comment]
![Uploading Fehler_2xgleicheChangeNr.JPG…]()

**Comment by mw-ft** [comment]
![fehler_2xgleichechangenr](https://cloud.githubusercontent.com/assets/17317785/20562616/c60cbeb4-b184-11e6-9865-9db49a92e699.JPG)
![fehler_2xgleichechangenr](https://cloud.githubusercontent.com/assets/17317785/20562578/9761e2ce-b184-11e6-8f82-98cd56d7f2ec.JPG)

**Comment by mw-ft** [comment]
Aktualisierung:
Auf Nachfrage ergab sich folgendes:
Der Kunde hat versucht, mit der gleichen ChangeNr eine 2. Bestellung anzulegen (weil Hin- und Rückrichtung seiner Meinung nach zusammen gehören. ABER bei uns auch abrechniúngstechnisch sind es ja 2 Channel, aslo 2 Change erforderlich!). Als das nicht ging (doppelte ChangeNr. wird ja nicht zugelassen) hat er sich einfach eine neue ChangeNr ausgedacht, alles eingetragen und zum schluß mit der Fkt "Bearbeiten" die ausgedachte ChangeNr wieder in die gewünschte geändert. Somit 2 Bestellungen unter einer ChangeNr beauftragt.
ABER das darf nicht sein, denn die ChangeNr. muss eineindeutig sein!
==> Es muss beim Ändern/anpassen verhindert werden, dass das ChangeNr-Feld korrigiert werden kann!!!

**Comment by automatix** [comment]
Das Problem ist/war, dass die Change-Nummer beim Eidtierungsformular (anders als bei der Erstellung) tatsächlich nicht darauf validiert wird, ob sie bereits vorhanden ist. Diese Überprüfung wurde bewusst herausgenommen, denn sonst könnten Formulare nicht geändert werden.

Nun wird das Feld im Editierungsformular auf `readonly` gesetzt. Da die Formatierung alleine keinen Schutz für die Formulardaten bietet (das Frontend lässt sich leicht überlisten), sondern lediglich dazu da ist, den Benutzer darauf hinzuweisen, dass das Feld nicht zu editierung ist, wurde die Speicherung angepasst, sodas die Change-Nummer der Änderungsspeicherung ignoriert wird.
