### ISSUE TITLE
LSP-Anzeige: nur die für das vorher ausgewählte FT-Produkt (also C:D oder FGW) gültigen anzeigen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#209]
## Bereich: 
Abrechnungs-Informationen
## User-Story
Der Besteller sieht nach Auswahl des Verfahrens oben rechts die nach ausgewählter Umgebung gültigen LSPs alle FT-Produkte (C:D und FGW)
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Da der Besteller aber schon vorher ausgewählt hat, ob er eine C:D-SST oder eine FGW-SST bestellen möchte sollen hier nur die für die jeweilige SST gültigen LSPs angezeigt werden.
Evtl. sollten auch weitere Info zu den LSPs mitangezeigt werden, z.B.  SL o.ä.

**Comment by automatix** [comment]
Das ist kein Bug, sondern ein nicht implementiertes (weil nicht geplantes) Feature. Ticket-Typ geändert.

**Comment by automatix** [comment]
implementiert
