### ISSUE TITLE
Formulare: WindowsShare: Benutzernamen (bei Quellsystem und Zielsystem) Anzahl soll unbegrenzt sein

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#211]
## Bereich: 
C:D und FGW Formulare: WindowsShare    Quellsystem und Zielsystem 

## User-Story
bei Zugriffseinstellungen - Benutzername
ist die max. Anzahl der Eingabefelder (über das + ) auf 10 begrenzt
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
bei Zugriffseinstellungen - Benutzername
soll eine unbegrenzte Liste zugelassen werden (statt der bisherigen Begrenzung auf 10 Felder)

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
14 Benutzer eingefügt, klappt:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24702703/4bce26a8-1a00-11e7-995e-b9c0dca60dc4.png)

**Comment by mw-ft** [comment]
Hier klappt auch remove:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24702723/6cf65eea-1a00-11e7-89de-0074f49a9ee7.png)
