### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#213]
## Bereich: 
Meine Bestellungen/Bestellungen
## User-Story
wenn viele Bestellungen bestehen, kann man sich nicht mehr gezielt ohne großen Aufwand eine bestimmte anschauen
siehe auch #26 und #53 und #54 
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
der Besteller und auch der Admin sollen innerhalb ihrer Bestellungen nach verschiedenen Suchbegriffe filtern können:
Endpoint, ChangeNr,  Umgebung, Verbindungstyp, Verfahren, Verzeichnis, Status ...
(Verbindungstyp, Status besonders auch für den Admin wichtig!)

ANMERKUNG für Ilya:
Das sollte nicht so aufwändig zu realisieren sein, denn man kann bestimmt die Suchfunktion vom Audit-Log nutzen!!!

**Comment by automatix** [comment]
abgelöst durch #285
