### ISSUE TITLE
FGW: selfService Felder FTGW-User und Mailbox keine Pflichtparameter!!!

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#215]
## User-Story

Als Frontend-User möchte ich, dass beim Formular FtgwSelfService die Felder "User" und "Mailbox" optional sind, sodass ich sie leer lassen und dennoch das (sonst korrekt ausgefüllte) Formular abschicken kann.

Hintergrund: Die Felder  FTGW-User und Mailbox sind keine Pflichtparameter für den Antragsteller. Diese werden von MW-FT festgelegt. Nur falls der Antragsteller schon eine entsprechende Mailbox/User hat, (oder er sich eine bestimmte wünscht) kann er in dieses in die beiden Felder schon eintragen.

Markierung und Validierung der Felder als Pflichtfelder FTGW-User und Mailbox entfernen!

## Akzeptanz-Kriterien
- Ich befinde mich auf der Formular-Seite `FtgwSelfService` zu `FtgwSelfService`.
- Ich sehe, dass das Feld "User" auf beiden Seiten optional ist (kein Stern).
- Ich sehe, dass das Feld "Mailbox" auf beiden Seiten optional ist (kein Stern).
- Ich fülle das Formular auf beiden Seiten korrekt und vollständig aus und lasse dabei auf beiden Seiten die Felder "User" und "Mailbox" leer.
- Ich klicke auf den Button <kbd>verbindlich Bestellen</kbd>
- [ ] Das formular wird abgeschickt.
- [ ] Es werden keine Fehlermeldungen bezüglich der nicht ausgefüllten Felder "User" und "Mailbox" angezeigt.

**Comment by automatix** [comment]
Das ist kein Bug, sondern ein Change-Request, deshalb den Ticket-Typ zu "Feature" geändert.

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
test ok,
kein * an den beiden Feldern und speichern/bestellen wird akzeptiert ohne Angaben in diesen Feldern:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24702983/828eaa18-1a01-11e7-8bd5-86f67dabc097.png)

Aber man kann auch Einträge in die beiden oder nur eins der beiden Felder machen:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24703043/c17d2be6-1a01-11e7-8c44-f94ff96b78a3.png)
