### ISSUE TITLE
WindowsShare: Benutzernamen zugefügte Felder wieder löschen (=Remove-Button) funktioniert nicht!

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#216]
## Bereich: 
Formular: WindowsShare 
## User-Story
Das mit Issue #194 eingebaute Remove von mit + Button zugefügten zusätzlichen Feldern für Benutzernamen durch Betätigen des - Buttons funktioniert seit der Erweiterung von max. 5 auf max. 10 Benutzernamen nicht mehr!!! 
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Remove-Button (- Button) muss das mit + Button zugefügte Feld für einen weiteren Benutzernamen wieder löschen!

aber unbegrenzte Liste siehe #211
 
## Akzeptanz-Kriterien
Wenn man - drückt, muss das vorher zugefügte Benutzernamen-Feld gelöscht werden (und ausgeblendet werden)

**Comment by automatix** [comment]
Der Fehöer lässt sich lokal nicht reproduzieren -- nach dem Betätigen des Buttons <kbd>-</kbd> verschwindet der dazu gehörde Block. Gibt es eine spezielle Konstellation, bei der der Fehler auftritt?

**Comment by mw-ft** [comment]
bei nochmaligen Testen tritt dieses Problem nicht mehr auf.
sehr komisch, aber der remove funktioniert!

**Comment by mw-ft** [comment]
Jetzt ist das Problem wieder da.
C7777777 im autofit = PRD
linke Seite 10 Felder zugefügt, gehen nicht wieder zu löschen
auch nicht nach Speichern und anpassen!!!

**Comment by automatix** [comment]
Konnte reproduziert und gefixt werden. Jetzt dürfte der Fehler nicht mehr auftreten.

**Comment by automatix** [comment]
ready for test

**Comment by mw-ft** [comment]
getestet: i.O.
