### ISSUE TITLE
C:D linux (extern - linux (intern): "verbindlich bestellen" funktioniert nicht

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#218]
## Bereich: 
C:D linux (extern - linux (intern): "verbindlich bestellen"
## User-Story
Formular ausgefüllt,  C30595355
speichern i.O. ?   zwar ohne Fehlermeldungen, aber wird wirklich gespeichert?
beim Button "verbindlich bestellen" wird aufgerufen: 
http://autofit.noncd.rz.db.de:88/order/process/create/cd/cdlinuxunix/cdlinuxunix
aber es passiert weiter nichts, d.h. es kommt keine Bestellbestätigung, aber auch keine Fehlermeldung!
Im Audit-Log ist zu der ChangeNr oder dem Besteller (iriskrueger) auch nichts zu sehen!
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
beim Button "speichern" und  "verbindlich bestellen" soll Bestellung kreiert und bestätigt werden!

**Comment by automatix** [comment]
Das Problem ist/war folgendes: Beim Auswählen von `Serverstandort=extern` wurden einige Pflicht-Felder geleert und ausgeblendet. Da diese Angabaen aber obligatorisch waren, wurde das Formular als nicht vollständig ausgefüllt betrachtet und das Abschicken browserseitig blockiert. (Eigentlich sollte dabei auch eine Meldung wie "Füllen Sie bitte dieses Feld aus" angezeigt werden.)

Nun wurden die Felder erstmal fakultativ gemacht, damit das Formular überhaupt abgeschickt werden kann. Im zweiten Schritt soll die Validierung an einer anderen Stelle implementiert werden (ähnlich wie für andere kontextabhängige Felder, z.B. `Server`).

**Comment by mw-ft** [comment]
Ist erledigt mit Deploy vom 28.03.2017 und funktioniert für C:D
Das gleiche Problem gibt es aber auch bei FGW, siehe dazu Issue #229

**Comment by automatix** [comment]
Der zweite Schritt is nun auch erledigt: Für die ausblendbaren Felder wurde die extra Validierung hinzugefügt. Lediglich die Include-Parameter betrifft das nicht, sie sind optional (werden aber nur gespeichert, wenn ausgefüllt).
