### ISSUE TITLE
Formular: INCLUDE-Parameter: Anzahl Felder "Ausdruck" unbegrenzt und Plausibilitäts-Check anpassen (Fehler bei <> )

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#221]
## Bereich: 
Formular: Feld Include-Parameter
## User-Story
1. Anzahl der Felder:
zur Zeit sind maximal 5 Felder "Ausdruck" bei dem Include-Parameter über +Button zugelassen und mit -Button wieder reduzieren möglich
2. Inhalt der Felder "Ausdruck" = erlaubte Zeichen
gibt man hier  Werte in < > an, dann verschwinden diese bei der Speicherung:
z.B. Eingabe:  N.P<jjmmtt>ABC   ->  es wird abgespeichert als: N.PABC

Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
1. unbegrenzte Anzahl der Felder "Ausdruck" über +Button zulassen und mit -Button wieder reduzieren ermöglichen
2. Die eingegeben Werte in den Feldern "Ausdruck" sollen zunächst auf Plausibilität d.h. gültige Zeichen für Ausdrücke (wir haben die Plausibilitätstabelle entsprechend ergänzt) gecheckt werden und wenn nicht gültige Zeichen eingegeben wurden, dann eine Fehlermeldung erzeugen.
Gültige Zeichen sind nur:       .     \    ^    $   -  +   *  ?   |   [   ]   A-Z   a-z   0-9
Alle laut Plausibilitäts-Check gültigen Zeichen müssen vollständig zur Speicherung übernommen werden.

**Comment by automatix** [comment]
Das Feature wurde anforderungsgemäß implementiert. Jetzt hat sich die Anforderung geändert und die Implementation soll entsprechend angepasst werden. Das ist jedoch kein Bug, sondern ein Change-Request und somit ein Feature-Ticket. Ticket-Typ geändert.

**Comment by automatix** [comment]
Kann den Fall mit "<", ">" und "N.PABC ->" nicht reproduzieren. Die Zeichen werden korrekt gespeichert, s. Bild.

![include-parameters](https://cloud.githubusercontent.com/assets/440005/24669215/dd29301c-1969-11e7-86a5-305c58970be4.png)

**Comment by automatix** [comment]
"_gibt man hier Werte in < > an, dann verschwinden diese bei der Speicherung:
z.B. Eingabe: N.PABC -> es wird abgespeichert als: N.PABC_" -- Ist das eine Feststellung eines unerwarteten Verhaltens oder eine Anforderung an das erwartete Verhalten?

**Comment by automatix** [comment]
Implementiert: Alle hier als gültig definierten Zeichen werden durchgelassen. Die ungültigen werden jedoch nicht abgeschnitten, sondern der User erhält, wie sonst aucbei einer invaliden Eingabe, eine entsprechende Fehlermeldung und kann erst die Bestellung abschicken, wenn das Feld, wie alle anderen auch, korrekt ausgefüllt ist. Sprich, aus "N.PABC ->" wird nicht als "N.PABC" abgespeichert, sondern gibt dem User einen Valisierungsfehler.

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
getestet: C66666666
 a Z 0 9 \ . - + * ? ( ) [ ] zulässig ( < oder > nicht zulässig, damit entfällt auch das evtl. Problem mit dem verschwinden von Zeichen)
 
![grafik](https://cloud.githubusercontent.com/assets/17317785/24701936/c91006f8-19fc-11e7-98c3-8c125c8e4afa.png)

**Comment by mw-ft** [comment]
ok!
