### ISSUE TITLE
Bestellungen: farbliche Markierung (Unterscheidung C:D-Anträge von FGW-Anträgen 

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#223]
## Bereich: 
Bestellungen
## User-Story
Bestellungen sehr unübersichtlich
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
die FGW-Bestellungen blau anzeigen, die C:D-Bestellungen komplett orange zur schnelleren Unterscheidung (evtl. nur als Übergangslösung bis eine Filterung #213 realisiert ist)

**Comment by mw-ft** [comment]
wäre noch etwas wichtig!

**Comment by automatix** [comment]
Inzwischen wurde sowohl Filterung&Sortierung, als auch im Rahmen des #284 die farbliche Markierung der Verbindungstypen implementiert. Das Ticket ist somit obsolet.
