### ISSUE TITLE
Jeder FE-User soll Reiter "Alle Bestellungen" haben

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#224]
## Bereich: 
User-Frontend
## User-Story
Jeder FE-User soll einen zusätzlichen Reiter "Alle Bestellungen" haben (so wie der Admin, aber hier nur mit Lesefunktion!)
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
FE-User soll dort alle fertiggestellten Anträge sehen (nicht die noch in Bearbeitung befindlichen!!!)
Diese Funktion mach aber erst Sinn, wenn die Suchfunktion #213 realisiert ist.

**Comment by automatix** [comment]
Implementiert. Damit die Änderung wirksam wird, muss die gecachte Konfigaration (`[project root]/data/cache/autoload_classmap.application.php`) gelöscht werden.
