### ISSUE TITLE
Dummy-Felder zulassen bei den Funktionen Speichern und Delegieren

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#225]
## Bereich: 
Formular: Antragserfassung
## User-Story
unterschiedliche Behandlung der Button "speichern" "delegieren"  (neuer Button) und "verbindlich bestellen"
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
FE-User kann einzelne Pflichtfelder leer lassen bzw. in den Auswahllisten wird zusätzlich zu den LSPs / Servern usw. auch DUMMY zur Auswahl angeboten, und trotzdem den Antrag speichern oder delegieren an einen weiteren "Ausfüller", obwohl nicht alle Pflichtfelder ausgefüllt sind.
Das gilt NICHT für "verbindlich bestellen" (Dazu müssen alle Pflichtfelder gültig ausgefüllt sein!

**Comment by automatix** [comment]
Die Anforderungen bilden eine Teilmenge der Anforderungen aus dem Ticket #5 (_Antrag-Zwischenspeicherung_), das inzwischen umgesetzt wurde. Das Ticket wird geschlossen.
