### ISSUE TITLE
C:D und FGW: WindowsShare: längere Namen zulassen und Plausibilitätscheck überprüfen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#226]
## Bereich: 
User-Frontend
## User-Story
Es gibt bereits längere Verzeichnisnamen, die nun nicht in das bisherige Formular eingetragen werden können:
z.B. Sharename: STRSPR-delete (genau 13 -> ginge also gerade noch, aber sicherheitshalber erhöhen auf 15)
aber z.B. im WindowsShare: DacsCD2017  das Schnittstellenverzeichnis: INTERNESTD_incoming sind 19 Zeichen

Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
1. Sharename: max. Länge erlauben: von bisher 13 auf 15 erhöhen 
2. (Schnittstellen)Verzeichnis: max. Länge erlauben von bisher 15 auf 20 erhöhen
3. Überprüfen der zugelassenen / nicht zugelassenen Zeichen entsprechend Plausibilitätscheck_Stand20170320.xls
Sharename  			Zeichen:  A-Z a-z 0-9 -   (keine Leerzeichen!)
Schnittstellenverzeichnis	Zeichen:  A-Z a-z 0-9 - _ (keine Leerzeichen!)

**Comment by automatix** [comment]
Das ist kein Bug, sondern eine nachträgliche Änderung. Ticket-Typ zu "Feature" umgeändert.

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
test:
1. Fehlermeldung, weil Felder zulang benutzt wurden:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24703822/349afa60-1a05-11e7-93d7-afdb883a1556.png)
2. Felder auf max. Länge benutzt:
OK, funktioniert:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24703856/68c147ea-1a05-11e7-81da-acde0f4ac8be.png)
