### ISSUE TITLE
zwei Links auf der Startseite des Bestellformulars anpassen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#227]
## Bereich: 
Startseite Bestellformular
## User-Story
Die Links: ' Leistungsbeschreibungen und Preise → laut "ICT Angebotskatalog V 1.2" ' 
und  ' Technische Details '  sind veraltet
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
1. Seite Bestellformular: 
a) Link: ' Leistungsbeschreibungen und Preise → laut "ICT Angebotskatalog V 1.2" ' ändern auf den allgemeiner Link zum Angebotskatalog: (damit bleibt der Link immer gleich, denn der Inhalt wird von Jahr zu Jahr angepasst):
https://dbsystel.intranet.deutschebahn.com/intra-dbsystel/start/leistungen/loesungen_und_produkte/ICT-angebotskatalog.html
b) Link: ' Technische Details '  ändern in: 
http://mw-doku1.noncd.rz.db.de/public/PR-FGW_LB_2012.pdf
Wir habe es schon mal direkt auf dem BLNSVA12158 in der index.html temporär geändert (09.03.2017) , aber es muss noch mal richtig durch git ... Versionierung
## Akzeptanz-Kriterien
jeder kann diese Links aufrufen

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
OK, es funktioniert.
Aber bitte bei Gelegenheit noch eine kleine Änderung:
den Namen gfür den Link ändern von  "ICT Angebotskatalog V 1.2"  auf  "ICT Angebotskatalog" , da der Link nun auf eine allgemeine Seite (ohne Versionsnummer) zeigt

**Comment by automatix** [comment]
erledigt
