### ISSUE TITLE
Formular C:D und FGW mit WindowsShare: als Servernamen nur die beiden wincdabn und wincdprd zulässig! 

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#228]
## Bereich: 
Formular: ausgewählte Seite WindowsShare
siehe im http://autofit2.noncd.rz.db.de:88     Change C12348754 für C:D und C23456789 für FGW
## User-Story
Wählt man C:D aus und dann auf einer Seite WindowsShare (fälschlicher weise anstatt Windows), so erscheint bei Servername (auf der Seite WindowsShare) die Auswahl wincdabn oder wincdprd (und nur auf diesen beiden richten wir WindowsShare ein) - soweit richtig.
ABER man kann dieses Feld mit einem anderen Servernamen überschreiben, auf denen wir gar keine SST mit WindowsShare einrichten z.B. ffmsrd99394 ! und dieser falsche Antrag wird auch ohne Probleme akzeptiert und gespeichert. Das ist falsch!
 
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Für die Seite, wo WindowsShare ausgewählt wurde, darf es nur die beiden Auswahlmöglichkeiten  wincdabn oder wincdprd geben. UND es muss abgesichert werden, dass der Antragsteller hier gar nicht erst einen anderen Server in das Feld Servernamen eintragen kann. 
(Oder wenigstens: es muss in dem Falle, dass der Antragsteller doch einen anderen Servernamen einträgt / eintragen kann, auf jeden Fall schon beim Speichern eine Fehlermeldung kommen: "Mit der Auswahl WindowsShare beantragen Sie nur die Nutzung eines Shares auf den MW-C:D-Servern wincdabn (für Abnahmeumgebung) oder wincdprd (für Produktionsumgebung), also deshalb in dem Fall nur aus diesen beiden auswählen! Wollen Sie jedoch eine FT-Verbindung mit einem Windows-Verfahrensserver bestellen, dann müssen Sie als Quell- bzw. Zielsystem statt WindowsShare    Windows  wählen!" und das Speichern verhindert werden).

## Akzeptanz-Kriterien
Änderung/Überschreibung der Servernamen wird verhindert. Es ist abgesichert, dass nur einer der beiden gewählt werden kann!

**Comment by mw-ft** [comment]
siehe Email von heute:
Als Muster gibt es im autofit2 den Change C12348754 zur Darstellung des Problems bei C:D und den Change C23456789 für FGW:
a)  C12348754 zur Darstellung des Problems bei C:D
Ich habe links Unix und rechts WindowsShare gewählt, dann zeigt er beim Klick in das Feld Servername auf der rechten (also der WindowsShare-)Seite die Auswahlmöglichkeiten
wincdabn.tech.rz.db.de und wincdprd.tech,rz,db,de richtig an, siehe hier:
Es soll und darf auch nur einer dieser beiden angezeigten C:D-Server ausgewählt werden!!!
ABER z.Z. kann der Besteller das Feld einfach überschreiben mit irgendeinem Servernamen (im Beispiel ffmsrd99394) und den Antrag auch ohne Fehler speichern und bestellen, siehe unten.
Das darf nicht sein!  
Es darf vom Besteller nur eine Auswahl aus den beiden angezeigten C:D-Server getroffen werden. Du musst verhindern, dass der Besteller in dieses Serverfeld bei WindowsShare irgendwas eigenes eintragen kann, d.h. dieses Feld darf nur aus der Auswahl gefüllt werden und keine Eingabe zulassen. 
Wenn das gar nicht machbar ist, müssen wir wenigstens eine Fehlermeldung generieren mit dem Text: 
Bei der Auswahl WindowsShare erfolgt der Transfer von oder zu einem Verzeichniss/Share auf einem der beiden C:D-Windows-Servern wincdabn (für die Abnahmeumgebung) und wincdprd (für die Produktionsumgebung). Nur einer dieser beiden Server ist bei WindowsShare auszuwählen.
Wollen Sie den Transfer von oder zu einem Verfahrens-Windows-Server bestellen, dann wählen Sie bei Quellsystem bzw. Zielsystem Windows aus!

**Comment by automatix** [comment]
Die gültigen Server für CDWindowsShare bzw. FTGWWindowsShare einzuschränken wäre etwas zu kurz gesprungen. Die Fragestellung sollte allgemeiner gafasst werden: Es werden (geerell für ale Formulare) zwar nur die gültigen Server angezeigt, jedoch wird nicht verhindert, dass der User selber einen (an sich gültigen, spricht, in der Datebank vorhandenen) Server angibt. Die Server-Validierung soll also um diesen Aspekt erweitert werden. Das ist kein Bug, sondern fehlende Funktionalität, die im Rahmen eines Feature-Tickets implementiert werden soll.

**Comment by mw-ft** [comment]
OK, es ist richtig, dass es im Moment so implementiert ist, dass zwar die Serverliste anhand der Auswahl BS Quell- und Zielsystem angezeigt wird, aber man in die Server-Felder durchaus einen anderen gültigen Server eintragen kann (z.b. im Unix-Formular blp1 was ein zOS-Server ist oder beim WindowsShare auch einen unix-Server usw.). Das wird nicht bemängelt und Speichern /bestellen geht ohne Fehleemeldung.
==> Entscheidung heute:
Wir lassen das erstmal so!
Dieser Issue wird nach ganz hinten gestellt, bzw dieser wird geschlossen.
automatix hat zur generellen Lösung ja bereits Issue #231 aufgemacht.
Als "Umgehungslösung" für das WindowsShare-Problem siehe Issue #232
