### ISSUE TITLE
FGW: Auswahl extern : "verbindlich bestellen" funktioniert nicht

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#229]
## Bereich: 

FGW: Auswahl extern: "verbindlich bestellen"

## User-Story

speichern und beim Button "verbindlich bestellen" wird aufgerufen:
aber es passiert weiter nichts, d.h. es kommt keine Bestellbestätigung, aber Fehlermeldung: Füllen Sie dieses Feld aus, aber es ist kein Feld da was fehlt.
Im Audit-Log ist zu der ChangeNr oder dem Besteller (iriskrueger) auch nichts zu sehen!
siehe auch Issue #218 
hier aber bei FGW!

beim Button "speichern" und "verbindlich bestellen" soll Bestellung kreiert und bestätigt werden!
Bitte alle anderen möglichen Varanten prüfen, wo dieses Problem noch auftreten könnte und beseitigen!

## Akzeptanz-Kriterien

Ich kann speichern und bestellen, wenn alle angezeigten Pflichtfelder (richtig) ausgefüllt sind!

**Comment by automatix** [comment]
Kann den Fehler nicht reproduzieren.

Das Formular FTGWLinuxUnix hat keine Serverstandort-Auswahl. Dort werden auch keine Pflicht-Felder ausgeblendet, sodass der Fehler (falls es der gleiche wie im #218 sein soll) eigentlich gar nicht auftreten kann.

**Comment by automatix** [comment]
Der Fehler tritt im Formular FTGWProtocolServer (Quelle) auf. Das ist zu fixen.

**Comment by mw-ft** [comment]
es geht hier beim FGW nicht um den Typ LinuxUnix sondern um alle Fälle wo man extern auswählen kann. z.B. Protokollserver, aber auch weitere. Bitte alle dahingehend korrigieren.

**Comment by mw-ft** [comment]
Ich habe die Issue-Beschreibung entsprechend angepasst.

**Comment by automatix** [comment]
Wie im Comment #issuecomment-290217568 angemerkt, trat der Fehler beim FTGWProtocolServer (Quelle) auf. Der Fehler wurde am selben Tag (des Comments) beseitigt. Das Ticket kann nun getestet und geschlossen werden.

**Comment by mw-ft** [comment]
Ist getestet und i.O.
Ich schreibe es in das Ticket rein und schließe es.

Best Regards / Mit freundlichen Grüßen

Iris Krüger
D.IPD 26 - IT Production Infrastructure and Holding II - Team Middleware

DB Systel GmbH
Florastraße 133-136, 12623Berlin
Tel. ++49 (0)30 297 16 146, intern 999--
Mobil: ++49 160 97487594
_________________________________________________________________________________

Der DB-Konzern im Internet >> http://www.deutschebahn.com

--- Bitte denken Sie an die Umwelt, bevor Sie diese E-Mail ausdrucken. ---

Sitz der Gesellschaft: Frankfurt am Main
Registergericht: Frankfurt am Main, HRB 78707
USt-IdNr.: DE252204770
Geschäftsführer: Christa Koenen (Vorsitzende), Bodo Gmel, Gerald Hofer, Dr.
Klaus Rüffler
Vorsitzender des Aufsichtsrates: Dr. Richard Lutz


|------------>
| Von:       |
|------------>
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
  |automatix <notifications@github.com>                                                                                                              |
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
|------------>
| An:        |
|------------>
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
  |dbsystel/AutoFIT <AutoFIT@noreply.github.com>                                                                                                     |
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
|------------>
| Kopie:     |
|------------>
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
  |mw-ft <iris.krueger@deutschebahn.com>, Author <author@noreply.github.com>                                                                         |
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
|------------>
| Datum:     |
|------------>
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
  |02.04.2017 15:01                                                                                                                                  |
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
|------------>
| Betreff:   |
|------------>
  >--------------------------------------------------------------------------------------------------------------------------------------------------|
  |Re: [dbsystel/AutoFIT] FGW: Auswahl extern : "verbindlich bestellen" funktioniert nicht (#229)                                                    |
  >--------------------------------------------------------------------------------------------------------------------------------------------------|





Wie im Comment #issuecomment-290217568 angemerkt, trat der Fehler beim
FTGWProtocolServer (Quelle) auf. Der Fehler wurde am selben Tag (des
Comments) beseitigt. Das Ticket kann nun getestet und geschlossen werden.
