### ISSUE TITLE
FGW: Protokollserver: alle spezifischen Endpoint-Felder unabhängig von Auswahl inter / extern anzeigen (keine dieser Felder ausblenden!)

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#230]
## User-Story

unter Verfahrensuser fehlt das Feld: Verzeichnis
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Bei Protokollserver  extern unter dem Feld Verfahrensuser das Feld: Verzeichnis eingebaut wird. Dieses ist aber kein!!! Pflichtfeld, kann also auch vom Besteller unausgefüllt gelassen werden.
d.h. nicht als Pflichtfeld markieren (kein * dran machen wie sonst üblich) und auch nicht auf Inhalt prüfen

**Comment by automatix** [comment]
Die Anforderung ist noch nicht ganz klar.

Ist-Zustand:
Quellenendpoint: bei Serverstandort=intern: Feld "Verzeichnis" gegeben und ist obligatorisch
Quellenendpoint: bei Serverstandort=extern: Feld "Verzeichnis" nicht gegeben
Zielendpoint: bei Serverstandort=intern: Feld "Verzeichnis" gegeben und ist obligatorisch
Zielendpoint: bei Serverstandort=extern: Feld "Verzeichnis" gegeben und ist obligatorisch

Wie ist der Soll-Zustand?
Quellenendpoint: bei Serverstandort=intern: Feld "Verzeichnis" gegeben**?** obligatorisch**?**
Quellenendpoint: bei Serverstandort=extern: Feld "Verzeichnis" gegeben**?** obligatorisch**?**
Zielendpoint: bei Serverstandort=intern: Feld "Verzeichnis" gegeben**?** obligatorisch**?**
Zielendpoint: bei Serverstandort=extern: Feld "Verzeichnis" gegeben**?** obligatorisch**?**

**Comment by mw-ft** [comment]
Beschreibung Formular ProtokollServer konkretisiert:
Die entweder-oder-Felder "intern" und "extern" sollen nur etwas über den Standort des ProtokollServers aussagen, nicht aber auf die im Formular angezeigten Felder wirken! d.h. es sollen immer die gleichen Felder zum Ausfüllen angezeigt werden.
In jedem Fall soll sowohl bei Quelle als auch bei Ziel unter dem Pflicht-Feld  Verfahrensuser das Feld Verzeichnis immer angezeigt werden. Dies Feld Verzeichnis ist aber kein Pflicht-Feld, d.h. es muss nicht ausgefüllt werden (also es ist    nicht obligatorisch = fakultativ). Deshalb soll es nicht mit blauem * gekennzeichnet sein.
Zur Erläuterung soll folgende zusätzliche Info angezeigt werden:
"Hinweis: Wird hier kein Verzeichnis angegeben, so wird als Daten-Verzeichnis für den Transfer das Home-Verzeichnis des Verfahrensuser verwendet!"

**Comment by automatix** [comment]
> Die entweder-oder-Felder "intern" und "extern" sollen nur etwas über den Standort des ProtokollServers aussagen, nicht aber auf die im Formular angezeigten Felder wirken! d.h. es sollen immer die gleichen Felder zum Ausfüllen angezeigt werden.

Nur um die Anforderung zu präzisieren und etwaigen unnötigen Aufwand zu vermeiden: Betrifft das nur das Feld "Verzeichnis" oder wirklich ALLE Felder, die momentan in Abhängigkeit vom Wert des Feldes "Serverstandort" ein- und ausgeblendet werden (also auch "Include-Parameter")?

**Comment by mw-ft** [comment]
Nach Beratung im Team: 
unabhängig von der Auswahl "extern" oder "intern" sollen ALLE SPEZIFISCHEN Endpoint-Felder angezeigt und gecheckt werden.

**Comment by automatix** [comment]
@mw-ft @dirkludwig2 @aleunam

Bei unserer Besprechung heute sind wir zum Schluss gekommen, dass das Verhalten wie folgt zu definieren ist:

Die Auswahl des Standorts (`intern`/`extern`) soll keine Auswirkung auf spezifischen Felder haben. Das gilt sowohl für CD, als auch für FTGW.

Deshlab wird dieses Ticket gecancelt und für die neue Anforderung ein anderes erstellt.
