### ISSUE TITLE
Endpointtypbezogene Server-Validierung

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#231]
## User-Story

Als Frontend-User möchte ich nur solche Server angeben können, die für den aktuellen Endpoint gültig (und somit in der Autocomplete-Vorschlagsliste drin) sind.

Momentan ist die Gültigkeitsüberprüfung nur darauf beschränkt, dass der angegebene Servername in der Datenbank vorhanden und der Server aktiv ist. Die Validierung soll also durch eine weitere Bedingung erweitert werden, nämlich die Zugehörigkeit zum aktuellen Endpoint-Typ (z.B. CDTandem oder FTGWWindowsShare).

## Akzeptanz-Kriterien

- Ich öffne das Formular CDTandem->CDWindowsShare.
- Ich wähle auf beiden Seiten bei QuellsystemGrundeinstellungen.Serverstandort "intern" aus.
- Ich trage auf beiden Seiten bei QuellsystemGrundeinstellungen.Servername jeweils einen gültigen (vorhandenen und aktiven) Server, der nicht dem Endpoint entspricht.
- Ich fülle das Formular sonst korrekt aus.
- Ich schicke das Formular ab.
- [ ] Das Formular wird wieder geladen und es erscheinen zwei Fehlermeldungen, dass der Server nicht korrekt ist.
- Ich trage links einen für CDTandem korrekten Server ein.
- Ich trage rechts einen für CDWindowsShare korrekten Server ein.
- Ich schicke das Formular ab.
- [ ] Das Formular wird akzeptiert.

**Comment by automatix** [comment]
Implemented. Ready for test.

**Comment by mw-ft** [comment]
![grafik](https://cloud.githubusercontent.com/assets/17317785/24702470/23b51588-19ff-11e7-8379-c578296ca499.png)

**Comment by mw-ft** [comment]
Eingaben auf gültige korrigiert:
![grafik](https://cloud.githubusercontent.com/assets/17317785/24702521/6739ce98-19ff-11e7-8d99-250b18dc4d87.png)
Speichern und Bestellen ok
