### ISSUE TITLE
Formular C:D und FGW : bei WindowsShare: sollen als Servernamen nur die beiden wincdabn und wincdprd verwendet werden

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#232]
## Bereich: 
C:D und FGW:
Formular C:D und FGW : bei WindowsShare: sollen als Servernamen nur die beiden wincdabn und wincdprd verwendet werden
## User-Story
Oft wird das Formular WindowsShare verwendet, obwohl Windows(Server) gemeint itst
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
In der Auswahliste Quell- und Zielsystem (bei C:D und bei FGW)
die Auswahlmöglichkeit  "WindowsShare" umbenannt wird in  "Share (nur für Server wincdabn bzw. wincdprd!)" 
und in der Auswahl angezeigt wird.
Dies ist eine "Umgehungslösung"zum Problem #228

**Comment by automatix** [comment]
erledigt durch #231.
