### ISSUE TITLE
Formular: Include-Parameter geänderte Plausibilitätsprüfung: alle Zeichen außer < > % zulassen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#235]
## Bereich: 
Formular: Include-Parameter 
## User-Story
Der Plausibilitätscheck der Ausdruck-Feldern zum Include-Parameter ist zur Zeit zu restriktiv
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
In den Ausdruck-Feldern zum Include-Parameter sollen alle Zeichen außer < > %  zugelassen werden
## Akzeptanz-Kriterien
Die Ausdruck-Feldern zum Include-Parameter sind nur fehlerhaft und werden als unakzeptabel abgelehnt, wenn sie die Zeichen  < > %  enthalten

**Comment by automatix** [comment]
implementiert
