### ISSUE TITLE
Formular C:D und FGW: Endpoint zOS: Blockgrößen-Höchstwert anpassen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#238]
## Bereich: 
Formular C:D und FGW: Endpoint zOS: 
## User-Story
zur Zeit ist der zulässige Höchstwert für die Blockgröße auf 27930 gesetzt, das ist zu niedrig
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
der zulässige Höchstwert für die Blockgröße soll auf 32756  gesetzt werden
siehe auch BLNSVA12158:\Data\MW1-Projekte\CD-FGW-Bestellportal\Plausibilitätscheck\ 
Datei: Plausibilitätscheck_Stand20170424.xls   (Zeile 22)

**Comment by automatix** [comment]
Es ist zu beachten, dass die Feld-Gruppe "Datei-Parameter" in mehreren Formularen vorhanden ist:

* `CdZos` (Ziel),
* `FtgwZos` (Ziel),
* `FtgwProtocolServer` (Ziel).

D.h. die Änderungen ist für all diese Formular-Typen relevant.

Die zulässige Obergrenze für die Block-Größe wurde angepasst.
