### ISSUE TITLE
Formular C:D und FGW: Endpoint (Windows)SHARE: Zugriffseinstellungen - Benutzername:  - auch als gültiges Zeichen zulassen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#239]
## Bereich: 
FGW + C:D-Formulare: System (Windows)SHARE: 
Zugriffseinstellungen - Benutzername
## User-Story
Bisher sind lt Plausibilitätscheck-Liste nur A-Z  a-z 0 - 9 und \ zulässig
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Es gibt aber auch User-/Gruppen-Namen, die das Minuszeichen   -    enthalten
also bei Zugriffseinstellungen - Benutzername : zusätzlich noch - erlauben als gültiges Zeichen
(seihe Plausibilitätscheck_Stand20170502.xls)

**Comment by automatix** [comment]
implementiert
