### ISSUE TITLE
Bestellportal - Startmenü : eventuell für alle Benutzer den Menüpunkt "Bestellungen" zulassen ?

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#241]
## Bereich: 
Bestellportal - Startmenü 
## User-Story
Zur Zeit kann ein "normaler" User (also ein Nicht-Admin) nur seine eigenen Bestellungen sehen, indem er auswählt "Meine Bestellungen"
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Wir haben überlegt, dass es sinnvoll ist, jedem User (so wie dem Admin) zusätzlich auch den Button "Bestellungen" zur Verfügung zu stellen, allerdings nur zur Anzeige aller im System befindlichen Bestellungen - natürlich ohne irgendwelche Button (wie anpassen/einreichen/stornieren/überprüfen/export usw.)
Allerdings erfordert dies dann sicher auch eine Suchfunktion innerhalb dieser vielen im System befindlichen Bestellungen/Changes ...
Das Thema sollte nochmal diskutiert werden!

**Comment by mw-ft** [comment]
PROBLEM _ FEHLER:
27.06.2017 IK:
Nun hat jeder normale User den zusätzlichen Button "Bestellungen"
Wenn er den Reiter auswählt, bekommt er die Übersichtsliste aller im System befindlichen Bestellungen. Sie haben keine Zugriffsrechte für diese Ansicht/Aktion.nn er dort eine ChangeNr anklickt, um den kompletten Antrag zu sehen, kann er sich aber das Formular nicht ansehen -> Es kommt eine Fehlerausschrift: Sie haben keine Zugriffsrechte für diese Ansicht/Aktion.

**Comment by automatix** [comment]
s. #224
