### ISSUE TITLE
C:D- und FGW-Bestellportal: ChangeNummer: Change-Unternummern zulassen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#242]
## Bereich: 
C:D- und FGW-Bestellportal: Formular: Bestellung einer Verbindung
## User-Story
Zwischen 2 Servern sind ggf mehrere Channel (in eine Richtung oder auch eine Hin- und eine Rückrichtung) einzurichten.
Da ist es für den Besteller einfacher, nur einen Change für mehrere Channel zwischen den gleichen Servern zu erstellen.

Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Deshalb sollen als Change-Nummer (auch) folgende zugelassen werden:
C12345678-01 ... C12345678-02 usw.
Wenn man es genau macht, müsste man dann, wenn ein Besteller diese "UnterNummern" verwendet, zusätzlich noch checken, ob die Quell- und Ziel-Server die gleichen sind. Quell- und Ziel-Server können auch vertauscht sein bei Bestellung von 2 Channeln (1 für Hin- und 1 für Rückrichtung)
Sind die beiden Server nicht die gleichen wie in anderen Changes mit der gleichen "OberNummer", dann muss eine Fehlermeldung kommen: "Je Server-Verbindung muss ein separater Change erstellt werden. Nur wenn zwischen zwei Servern mehrere Channel betellt werden sollen, kann das mit einem Change erfolgen. Für die entsprechenden SchnittstellenAnträge können die Change"UnterNummern" verwendet werden."

## Zusatzanforderung/Seiteneffekt

- [ ] Das Feld "Change-Nummer" beim Bestellformular soll zusätzlich zum Muster "Buchstabe + 8 Ziffern" das Muster "Buchstabe + 8 Ziffern + Punkt + eine Ziffer" akzeptieren.
- [ ] Das Feld "Change-Nummer" beim SuchFormular soll zusätzlich zum Muster "Buchstabe + 8 Ziffern" das Muster "Buchstabe + 8 Ziffern + Punkt + eine Ziffer" akzeptieren.
- [ ] Sucht der User nach `C12345678`, sollen ihm all Formulare angezeigt werden, deren Change-Nummern diese Zeichenfolge enthalten (also `LIKE C12345678%`), d.h. es wird nach der Change-Nummern und allen Sub-Change-NUmmern gesucht.

**Comment by automatix** [comment]
Implementiert.

Zur Info:

- Nach dem Punkt sind Zahlen `1-9` zulässig.
- GEsucht wird nach `LIKE %ANGEGEBENE_CHANGE_NUMMER%`
