### ISSUE TITLE
Lockerung der Anzeige-Regeln für die Felder des Abrechnungsblocks

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#248]
## User-Story

Als Frontend-User möchte ich, dass mir

- alle gültigen Verfahren,
- alle zu dem ausgewählten Verfahren gehörenden Umgebungen
- sowie alle zu den ausgewählten Verfahren und Umgebung gehörenden gültigen LSPs (das wird erstmal beibehalten, die Ermöglichung der Auwahl ungültiger LSPs ist nicht Bestandteil dieses Tickets, s. #249)

angezeigt werden, damit die Autovervollständigung so wenige wie möglich versteckte Logik enthält.

## Hintergrund

Entsprechend der Anforderung des #204 soll ein Verfahren dem User nur dann zur Verfügung gestelt werden, wenn es mindestens eine gültige LSP (`basic` und `personal`) dafür gibt. Vorteil: Man kriegt nur das vorgeschlagen, was man verwenden kann. Nachteil: Falls der User nicht an die Stückzahl (oder andere Faktoren, die eine LSP und somit ggf. das Verfahren ungültg für die Auswahl machen könnten) denkt, wundert er sich u.U., warum sein Verfahren nicht angezeigt wird, obwohl er doch weiß, dass dieses vorhanden ist und es dafür LSPs gibt.

## Akzeptanz-Kriterien

s. User-Story

**Comment by automatix** [comment]
Ready for test.

**Comment by mw-ft** [comment]
OK, siehe auch #249 und #256
