### ISSUE TITLE
Anzeige ungültiger LSPs

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#249]
## User-Story

Als Frontend-User möchte ich, dass in den LSP-Autocomplete-Feldern auch die ungültigen LSPs mitangezeigt bzw. zur Auswahl angeboten werden, sodass ich erstmal all meine LSPs zu den ausgewählten Verfahren und Umgebung sehe.

Beim Auswählen einer ungültigen LSP soll jedoch die Vlidierung das Abspeichern des Formulars weiterhin verhindern.

<strike>!!! Außerdem muss verhindert werden, dass der Antragsteller ein LSP händisch eintragen kann, d.h. es ist ihm nur eine Auswahl aus der angezeigten Liste erlaubt und KEIN Reinschreiben eines "eigenen" LSPs!</strike>
siehe [Kommentar](249#issuecomment-310196283).

## Akzeptanz-Kriterien

- Ich gehe auf eine beliebige Formular-Seite, z.B. `AS400->AS400`.
- Ich trage ein gültiges Verfahren ein bzw. wähle eins aus.
- Ich trage eine Umgebung ein bzw. wähle eine aus.
- Ich setze den Cursor ins Feld `LSP-S`.
- [ ] Mir werden alle Basis-LSPs zum ausgewählten Verfahren&Umgebung angezeigt.
- Ich wähle eine ungültige (inaktive (`status = "Beendet"`) oder nicht verfügbare (`quantity = 0`)) LSP aus.
- Ich schicke das (sonst valide) Formular ab.
- [ ] Die Daten werden nicht akzeptiert und ich bekomme eine Validierungsmeldung, dass der Wert für das Feld `BasisLSP` ungültig ist.

Das gleiche Verfahren bei Feld 'LSP-P' anwenden!!!

**Comment by mw-ft** [comment]
Wir müssen auf jeden Fall auch verhindern, dass der Antragsteller irgendein "eigenes" LSP in das Feld einträgt. 
durch:
entweder Er darf nur aus der jeweils für VerfahrenUmgebung angezeigten Liste ein LSP auswählen und kann in die beiden LSP-Felder nichts reinschreiben
oder wenn das programmtechnisch nicht ins Konzept passt, weil du diese Felder nicht gegen händische Eingabe schützen kannst und der Antragsteller deshalb doch irgendetwas eintragen kann, dann muss eben bei der Validierung geprüft werden, ob das eingegebene LSP ein für Verfahre&Umgebung gültiges ist.

**Comment by automatix** [comment]
Die Variante a. ist etwas aufwändiger. Die Variante b. kann dagegen analog zu anderen validierten (Autocomplete-)Feldern umgesetzt werden. Ich würde sie bevorzugen.

Wenn wir das Verhalten der LSPs-Autovervollständigung ändern, sollte man überlegen, ob nicht auch die  restlichen Felder nach dem selben Prinzip angepasst werden.

**Comment by automatix** [comment]
Ready for test.

Es werden nun alle für das aktuell ausgewählte Paar Verfahren&Umgebung relevanten LSPs (`basic` bzw. `personal`) angezeigt. Auch manuelle Eingabe ist möglich.

Wird jedoch versucht, das Formular mit einer ungültigen LSP zu speichern, wird die Anfrage mit Fehlermeldung abgelehnt. `Ungültig` soll hier heißen, dass mindestens eine der folgenden Aussagen für die LSP zutrifft:

- nicht dem ausgewählten Verfahren entsprechend ODER
- nicht der ausgewählten Umgebung entsprechend ODER
- nicht dem aktuellen Verbindungstyp (CD|FTGW) entsprechend ODER
- nicht dem Artikel-Typ (basis|personal) entsprechend
- nicht verfügbar (`quantity = 0`)
- nicht aktiv (`status = "Beendet"`)

**Comment by mw-ft** [comment]
Soweit i.O.,
aber die Fehlermeldung für ungültige Basis- bze. Personal-LSPs sollte konkret den Ungültigkeitsgrund anzeigen:
entweder
LSP ungültig, weil LSP beendet bzw. Stückzahl = 0 ist
oder
LSP ungültig! (d.h. es wurde eine Ziffernfolge gewählt wofür es keine passende LSP gibt)
Anforderung wird in neuem Ticket konkretisiert -> Ilya

**Comment by automatix** [comment]
@mw-ft #256
