### ISSUE TITLE
Formular C:D und FGW:  Quell- und / oder Zielsystem mehrere Server Cluster-Server anzeigen 

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#251]
## Bereich: 
Im Bestellformular für C:D oder FGW bei Auswahl (Quell-/Ziel-)System Lunix/Unix gibt es bei Server-Variante (da ist übrigens ein Schreibfehler drin) die Auswahlmöglichkeit: mehrere Server
## User-Story
Wählt man mehrere Server
kann man entweder einen neuen Cluster definieren oder
sich die Liste der schon definierten Cluster durch Klicken in das Feld "Virtueller Knotenname des Clusters" anzeigen lassen und ggf dort eine schon bestehendes Cluster auswählen.
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Hier sollen zu dem schon (evtl. von anderen Antragstellern definierten) Cluster auch die in diesem Cluster zugehörigen Servernamen angezeigt werden. Das ist insbesondere erforderlich, weil der neue Antragsteller ja für gleiche Server kein neues Cluster definieren kann und er so schon sehen kann, welche Server schon in einem und in welchem Cluster definiert sind
## Akzeptanz-Kriterien
Für schon bestehende Cluster werden die zugehörenden Servernamen angezeigt.

**Comment by automatix** [comment]
Wie besprochen, wird das Problem mit einer separaten Info-Seite gelöst. Dazu wurde ein Ticket estellt (s. #253).

**Comment by mw-ft** [comment]
Hier wurde also nichts bearbeitet, sondern zu dem genannten Problem nur ein neues konkretes Ticket #253 aufgemacht und dieses geschlossen. -> i.O.
