### ISSUE TITLE
C:D und FGW-Formulare Quell- / Zielsystem Typ: Share

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#257]
## Bereich: 
Feld: Schnittstellenverzeichnis
## User-Story
in das Feld zum Eintragen des Schnittstellenverzeichnisses versuchen die Antragsteller oft in\\ \<sstverz>  bzw out\\ \<sstverz> einzugeben, weil der komplette Pfad z.B. so heißt:
<lw:> \daten\ALFDATEN\in\DWH
dabei ist ALFDATEN der Sharename und DWH das Schnittstellenverzeichnis
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
vor dem Feld zum Eintragen des Schnittstellenverzeichnisses soll noch unveränderbar stehen:
\in\  wenn auf der Zielserver-Seite Share gewählt wurde
\out\ wenn auf der Quellserver-Seite Share gewählt wurde
gleich rechts daneben soll jeweils das Eingabefeld für das Schnittstellenverzeichnisses sein  (wo der Antragsteller dann z.B. nur noch DWH eingeben kann/darf)

Analog könnte man das auch für  Sharename machen, das dem der fester Text vorangestellt wird:
\daten\

**Comment by automatix** [comment]
Wie soll konkret die Regel für das Feld `Schnittstellenverzeichnis` für Quelle bzw. Ziel lauten?
