### ISSUE TITLE
FEHLER:  FGW  selfService - selfService bricht ab

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#258]
## Bereich: 
autofit2 (TEST) FGW
## User-Story
Auswahl: FGW dann Quell- und Zielsystem selfService
dann bricht es ab:
HTTP Error 500.0 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.
Es scheint alle Formulare zu betreffen, wenn man selfService gewählt hat
(Andere FGW-Formulare funktionieren)
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
keinen Abbbruch!!!

**Comment by automatix** [comment]
Gefixt (noch nicht deployt).
