### ISSUE TITLE
Share-Benutzername wird bemängelt, ist aber i.O. eingegeben

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#259]
## Bereich: 
autofit2 (TEST)
z.B. Bestellung einer FTGW-Verbindung von Linux/Unix zu Share
## User-Story
bei benutzername gebe ich iriskrueger ein und bekomme Fehlermeldung: 
Benutzername: Die Eingabe darf nur folgende Zeichen enthalten: "a-z", "A-Z", "0-9", "\", "-".
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Der Benutzername ist korrekt eingegeben, also keine Fehlermeldung, sondern akzeptieren

**Comment by automatix** [comment]
Das ist das gewünschte Verhalten, denn der Benutzername soll (laut Excel-Regeln) die Domäne enthalten, also z.B. `BKU\myname`.
