### ISSUE TITLE
Abrechnung: Eingabe einer aus LSP-Sicht ungültigen Umgebung ausgewählt führt zu fehlerhaften Aufträgen

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#260]
## Bereich: 
Abrechnung

## User-Story
Wählt man ein gültige Verfahren z.B. AG 141 aus und klickt dann rechts auf Umgebung: dort wird nur Wartung und Produktion angezeigt.
Wählt man Wartung und wählt dann die für Wartung angezeigten LSPs aus 
ändert danach per händischem Eintragen Wartung z.B. in Abnahme kommt beim Speichern der Fehler:
Füllen Sie dieses Feld aus! und zeigt auf das Feld  LSP-S, das nun geleert angezeigt wird (richtig, da es ja für die Abnahme kein gültiges LSP gibt) Darunter steht aber in dem "Scrollfeld eingeblendet noch die LSP-S von der Warzung, die ich dann wieder auswählen könnte - das ist aber falsch! Auch ins LSP-P-Feld dann reingeklickt bietet er mir das Wartungs-LSP zur Auswahl an. Wähle ich diese beiden Angebote aus, kann ich erfolgreich speichern. Hinterher sehe ich dann (mehr zufällig, wenn ich meine Bestellung nochmal ansehen) dass aus meiner gewünschten Umgebung Abnahme als Umgebung Wartung abgespeichert wurde:
C99998887
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
Wenn jemand eine andere als die auf der Basis gültiger LSPs möglichen Umgebung eingibt (das Auswahlfeld mit eigebenem Text überschreibt, darf das nicht akzeptiert werden. Wenn dann die Fehlermeldung kommt: Füllen Sie dieses Feld aus (gemeint ist das LSP-Feld) dann darf dort nicht die vorher für eine andere Umgebung verwendete LSP als Auswahl angezeigt werden, sondern die Liste muss leer sein (weil es in diesem Fall für die Abnahme kein gültiges LSP gibt!)

**Comment by automatix** [comment]
Auf eine einfache Weise gelöst: das unsichtbare Feld `UmgebungsID` sowie die LSP-Felde werden geleert `onFocus` des Felds `Umgebung`.
