### ISSUE TITLE
DRINGEND: FTGW-Verbindung von Protokoll-Server zu Linux/Unix - Speichern bricht ab!!!

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#262]
## Bereich: 
FTGW-Verbindung von Protokoll-Server zu Linux/Unix kann nicht gespeichert werden
Es kommt der Fehler: HTTP Error 500.0 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.
bzw. ....versuchen Sie es später noch mal!
das Problem ist generell das FGW-Formular mit Typ Protokoll-Server (Quelle oder Ziel)
Wir hatten es bei:
FTGW-Verbindung von Protokoll-Server zu Linux/Unix
und jetzt auch bei:
FTGW-Verbindung von Share zu Protokoll-Server
## User-Story
s.o.
Am 12.07.17 wurde ein analoger Antrag (siehe C30632010)  ohne Probleme erfasst und gespeichert!
(Hier hat wohl jemand etwas "verschlimmbessert"!)
Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}
dass es wieder funktioniert
## Akzeptanz-Kriterien
Es kann wieder gespeichert werden!

**Comment by mw-ft** [comment]
das Problem ist generell das FGW-Formular mit Typ Protokoll-Server (Quelle oder Ziel)
Wir hatten es bei:
FTGW-Verbindung von Protokoll-Server zu Linux/Unix
und jetzt auch bei:
FTGW-Verbindung von Share zu Protokoll-Server

**Comment by automatix** [comment]
Die Problem-Ursache lag in der falschen (und deshalb fehlschlagenden) Instanziierung eines Objekts (`Hydrator`), das die Protokoll-RadioButton-Daten für die Abspeicheung in der Datenbank konvertiert.

Gefixt und deployt auf TEST und PROD.
