### ISSUE TITLE
DRINGEND: Bestellung einer CD-Verbindung von Windows zu ZOS  (z.B. beide extern) bricht bei Speichern ab!

### ISSUE THREAD

**Issue by mw-ft** [dbsystel/AutoFIT#264]
## User-Story

Als {ROLLE} möchte ich {AKTION}, sodass {AKTION}

**Comment by mw-ft** [comment]
![issue264](https://user-images.githubusercontent.com/17317785/28923798-8fd80d6a-785f-11e7-9596-41f6edbd4d03.JPG)

**Comment by automatix** [comment]
fixed
