### ISSUE TITLE
Erweiterung Portal Endpointtyp / Formular AWS S3 Bucket

### ISSUE THREAD

**Issue by dirkludwig2** [dbsystel/AutoFIT#279]
## User-Story: 
Ein zusätzlicher Endpoint für Filegateway und zugehöriges Formular für Quelle/Ziel von und zu einem AWS S3-Bucket - ähnllich Windows-Share
Parameter:
Hostname ( Liste mit 1 Element - Servertyp awss3bucket )
Bucketname ( entspr. Share )
Folder ( entspr. Verzeichnis )
AWS-Key

**Comment by automatix** [comment]
@dirkludwig2 @dbsystel/mwft Implementiert und auf TEST deployt.

**Comment by automatix** [comment]
Doku folgt.

**Comment by automatix** [comment]
Integrationstest implementiert. Dokumentation erstellt.
