### ISSUE TITLE
CD|FTGW WindowsShare: Korrektur der Validierungsregel für das Feld "Sharename" TODO

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#290]
## Beschreibung

Im Formular `CD|FTGW WindowsShare` lautet die Regel für das Feld `Sharename` wie folgt: `/^[a-zA-Z0-9\-]*$/`, d.h. es sind Klein- und Großbuchstaben sowie Ziffern und Bindestriche zulässig. Die Validierung funktioniert ordnungsgemäß, die Fehlermeldung ist korrekt.

Die Regel soll um Unterstriche erweitert werden.

**TODO**: @dirkludwig2 Ist das korrekt?
DONE: Der Bindestrich soll weg und durch Unterstrich ersetzt werden, also `/^[a-zA-Z0-9_]*$/` anstatt von `/^[a-zA-Z0-9\-]*$/` (s. [Kommentar](290#issuecomment-347827195)).

**Comment by aliceholz** [comment]
Meiner Meinung nach dürfen keine Bindestriche zugelassen werden, sondern nur Unterstriche
