### ISSUE TITLE
Erweiterung der Listenansicht

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#292]
## User-Story

Als Frontend-User möchte ich, dass die Anträge der Liste der Bestellungen (in den Bereichen `Bestellungen` und `meine Bestellungen`) um folgende Informationen erweitert werden:

- [x] Benutzer
- [x] Sharename (relevant nur für `CD|FTGW WindowsShare`)

TODO: @mw-ft @dbsystel/mwft
DONE: s. [Comment](292#issuecomment-347826349)

**Comment by aliceholz** [comment]
beim Share sollte zusätzlich zum Verzeichnis auch der Sharename erscheinen
Bsp.:
http://autofit.noncd.rz.db.de:88/order/show/708
Verzeichnis in der Liste nur "leipro"
richtig wäre eig "SAPR3NETZA21 leipro"
