### ISSUE TITLE
Suche in "meine Bestellungen": Einschränkung der Autovervollständigung für Verfahren und Change-Nummer

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#298]
## User-Story

Als Frontend-User möchte ich, dass mir im Bereich "meine Bestellungn" in den Feldern "Verfahren" und "Change-Nummer" nur die Verfahren bzw. Change-Nummern angezeigt werden, die bereits für in meinen Bestellungen verwendet werden.

TODO: Nachdem weitere Suchfelder hinzugekommen sind, stellt sich die Frage: Ist diese Einschränkung wirklich sinnvoll? Denn dann müsste man bei den Feldern `ChangeNummer`, `Umgebung`, `Server` etc. genauso vorgehen.
DONE: Obsolet, da der Bereich "Meine Bestellungen" entfernt werden soll (s. #303).

**Comment by aliceholz** [comment]
ich denke die suchfunktionen für "meine Bestellungen" und "alle Bestellungen" sollten gleich gehalten werden, also ohne eine vorfilterung bei "meine Bestellungen".
wenn nichts gefunden wird, sollte meiner meinung nach, der satz "keine passenden Datensätze zu den Suchkriterien gefunden" erscheinen.

**Comment by automatix** [comment]
Da der Bereich "Meine Bestellungen" entfernt werden soll (s. #303), ist das Ticket obsolet.
