### ISSUE TITLE
Formatierung der Sortierung

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#299]
## User-Story

Als Frontend-User möchte ich, dass die Sortierung weniger Platz einnimmt, sodass das Suchformular mehr platz für die Filter bekommt.

## Anforderungen

- [x] Der Block "Sortierung" soll auf die Hälfte (auf `col-md-2`) reduziert werden.
- [x] Die Labels sollen wie folgt angepasst werden:
  - [x] "Datum und Zeit der Bestellung" -> "Bestelldatum"
  - [x] "absteigend" -> "▲" (`&#x25B2;`)
  - [x] "aufsteigend" -> "▼" (`&#x25BC;`)
- [x] Die Breite des Filter-Blocks soll um zwei Einheiten (auf `col-md-9`) erhöht werden.

![search-sort-formatting](https://user-images.githubusercontent.com/440005/32952912-e892178c-cbae-11e7-8d2d-678296cc0ca7.png)

TODO: @mw-ft @ttenno Passt das so?
DONE: Ja

**Comment by aliceholz** [comment]
meiner meinung nach vollkommen ok
