### ISSUE TITLE
Filterung der Listenansicht der Anträge (Datum, Antragsteller)

### ISSUE THREAD

**Issue by automatix** [dbsystel/AutoFIT#53]
## User-Story
==> alles zu #213 SUCHFUNKTION !!!
Als BE-User möchte ich die Möglichkeit haben, die Auflistung der Anträge (nach dem Eingangsdatum und dem Antragsteller, ChangeNr)  zu filtern.

**Comment by mw-ft** [comment]
ChangeNr

**Comment by automatix** [comment]
abgelöst durch #285
